services:

  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - eco-network
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    networks:
      - eco-network
    ports:
      - 5000:5000
    env_file:
      - .env
    working_dir: /usr/src/recyclable
    depends_on:
      - db
    
networks:
  eco-network:
    name: eco-network
    driver: bridge

volumes:
  pg: # volume para os postgres