services:
  db:
    image: postgres
    container_name: db
    networks:
      - eco-network
    ports:
      - 5433:5432
    env_file:
      - .env

  node_app:
    container_name: node_app
    build: .
    networks:
      - eco-network
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db

