services:
  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - network-eco
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
networks:
  network-eco:
    name: network-eco
    driver: bridge

volumes:
  pg: # volume para os postgres